set-option -g default-terminal "xterm-256color"
set-window-option -g xterm-keys on

# Tell tmux to support True Color (Tc) -- needed for older tmux versions
set -ga terminal-overrides ",xterm-256color:Tc"

unbind C-b
set-option -g prefix C-a
bind-key C-a send-prefix
bind-key C-a last-window

# Passes focus event through tmux
set -g focus-events on

set -g set-clipboard on
set -g mouse on
set -g base-index 1
set-option -g repeat-time 0

set-window-option -g mode-keys vi
bind -T copy-mode-vi v send-keys -X begin-selection

bind-key -T copy-mode-vi y send-keys -X copy-pipe-and-cancel 'pbcopy'
bind-key -T copy-mode-vi Enter send-keys -X copy-pipe-and-cancel 'pbcopy'

# follow hyperlinks
set -as terminal-features ",*:hyperlinks"

# vim-like pane switching
bind -r ^ last-window
bind -r k select-pane -U
bind -r j select-pane -D
bind -r h select-pane -L
bind -r l select-pane -R

# vim-like pane resizing
bind -r C-k resize-pane -U 15
bind -r C-j resize-pane -D 15
bind -r C-h resize-pane -L 15
bind -r C-l resize-pane -R 15

# swap windows
bind-key -n S-Left swap-window -t -1
bind-key -n S-Right swap-window -t +1

# Reload
bind r source-file ~/.tmux.conf

set -g visual-activity off
set -g visual-bell off
set -g visual-silence off
setw -g monitor-activity off
set -g bell-action none

# Lotus Palette Variables
# Background: #f2ecbc (lotus_white_3)
# Foreground: #545464 (lotus_ink_1)

# Pane borders
set -g pane-border-style "fg=#8a8980"           # lotus_gray_3
set -g pane-active-border-style "fg=#4e8ca2"    # lotus_teal_1

# Status bar general layout
set -g status-position bottom
set -g status-justify left
set -g status-style "fg=#545464 bg=#f2ecbc"     # lotus_ink_1 on lotus_white_3

# Left status (Session name block)
set -g status-left "#[fg=#f2ecbc,bg=#4e8ca2,bold] #S #[fg=#4e8ca2,bg=#f2ecbc,nobold] "
set -g status-left-length 20

# Right status (Date & Time)
set -g status-right-style "fg=#716e61 bg=#f2ecbc" # lotus_gray_2
set -g status-right "#[fg=#5e857a] %Y-%m-%d #[fg=#716e61]│#[fg=#43436c,bold] %H:%M "
set -g status-right-length 50

# Active window tab
setw -g window-status-current-style "fg=#f2ecbc bg=#b35b79 bold" # lotus_pink
setw -g window-status-current-format " #I:#W#F "

# Inactive window tabs
setw -g window-status-style "fg=#545464 bg=#f2ecbc"
setw -g window-status-format "#[fg=#4e8ca2] #I #[fg=#545464]#W "

# Window bell alert
setw -g window-status-bell-style "fg=#c84053 bg=#f2ecbc bold" # lotus_red

# Message / Command prompt line
set -g message-style "fg=#f2ecbc bg=#43436c bold" # lotus_ink_2

